import { Verifier } from "./types";

export const TestVerifiers: Verifier[] = [
  {
    id: "1",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "2",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "3",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "4",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "5",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "6",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "7",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "8",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "9",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "10",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "11",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "12",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "13",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "14",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "15",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
  {
    id: "16",
    firstname: "Sepehr",
    lastname: "Parsa",
    rate: "5.0",
    transactions_participated_count: 500,
  },
];
